name: MLOps workflow
on: push
jobs:
  build-ingest:
    name: 'Build Stage 1: Ingest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-ingest
      - uses: actions/upload-artifact@v2
        with:
          name: stage1_ingest
          path: stage1_ingest.zip
  # build-clean:
  #   if: always()
  #   name: 'Build Stage 2: Clean'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: ./.github/actions/build-clean
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: stage2_clean
  #         path: stage2_clean.zip
  build-model:
    name: 'Build Stage 3: Model'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-model
      - uses: actions/upload-artifact@v2
        with:
          name: stage3_model
          path: artifacts/*
  build-test:
    name: 'Build Stage 4: Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-test
      - uses: actions/upload-artifact@v2
        with:
          name: stage4_test
          path: stage4_test.zip
  build-deploy:
    name: 'Build Stage 5: Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-deploy
      - uses: actions/upload-artifact@v2
        with:
          name: stage5_deploy
          path: stage5_deploy.zip
  upload-artifacts:
    if: always()
    needs: [build-ingest, build-clean, build-model, build-test, build-deploy]
    name: 'Upload Build Artifacts to S3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: ./.github/scripts/collect-build-artifacts.sh

