name: MLOps workflow
on: push
jobs:
  build-ingest:
    name: Build Ingest Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-ingest
      - uses: actions/upload-artifact@v2
        with:
          name: ingest
          path: ingest.zip
