name: MLOps workflow
on: push
jobs:
  configure-workflow:
    name: 'Configure workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: pipeline-has-changed
        with:
          paths: pipeline
      - uses: marceloprado/has-changed-path@v1
        id: stage1-has-changed
        with:
          paths: pipeline/stage1_ingest
      - uses: marceloprado/has-changed-path@v1
        id: stage2-has-changed
        with:
          paths: pipeline/stage2_clean
      - uses: marceloprado/has-changed-path@v1
        id: stage3-has-changed
        with:
          paths: pipeline/stage3_model
      - uses: marceloprado/has-changed-path@v1
        id: stage4-has-changed
        with:
          paths: pipeline/stage4_test
      - uses: marceloprado/has-changed-path@v1
        id: stage5-has-changed
        with:
          paths: pipeline/stage5_deploy
    outputs:
      pipeline-has-changed: ${{ steps.pipeline-has-changed.changed }}
      stage1-has-changed: ${{ steps.stage1-has-changed.changed }}

        
  build-ingest:
    if: ${{ needs.configure-pipeline.outputs.stage1-has-changed }}
    name: 'Build Stage 1: Ingest'
    needs: configure-pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: pipeline/stage1_ingest
      - uses: ./.github/actions/build-ingest
        if: steps.has-changed.outputs.changed == 'true'
      - uses: actions/upload-artifact@v2
        if: steps.has-changed.outputs.changed == 'true'
        with:
          name: stage1_ingest
          path: stage1_ingest.zip
  build-clean:
    name: 'Build Stage 2: Clean'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: pipeline/stage2_clean
      - uses: ./.github/actions/build-clean
        if: steps.has-changed.outputs.changed == 'true'
      - uses: actions/upload-artifact@v2
        if: steps.has-changed.outputs.changed == 'true'
        with:
          name: stage2_clean
          path: stage2_clean.zip
  build-model:
    name: 'Build Stage 3: Model'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: pipeline/stage3_model
      - uses: ./.github/actions/build-model
        if: steps.has-changed.outputs.changed == 'true'
      - uses: actions/upload-artifact@v2
        if: steps.has-changed.outputs.changed == 'true'
        with:
          name: stage3_model
          path: artifacts/*
  build-test:
    name: 'Build Stage 4: Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: pipeline/stage4_test
      - uses: ./.github/actions/build-test
        if: steps.has-changed.outputs.changed == 'true'
      - uses: actions/upload-artifact@v2
        if: steps.has-changed.outputs.changed == 'true'
        with:
          name: stage4_test
          path: stage4_test.zip
  build-deploy:
    name: 'Build Stage 5: Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: pipeline/stage5_deploy
      - uses: ./.github/actions/build-deploy
        if: steps.has-changed.outputs.changed == 'true'
      - uses: actions/upload-artifact@v2
        if: steps.has-changed.outputs.changed == 'true'
        with:
          name: stage5_deploy
          path: stage5_deploy.zip
  upload-artifacts:
    environment: Production
    needs: [build-ingest, build-clean, build-model, build-test, build-deploy]
    name: 'Upload Build Artifacts to S3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: pipeline 
      - uses: actions/download-artifact@v2
        if: steps.has-changed.outputs.changed == 'true'      
      - run: ./.github/scripts/collect-build-artifacts.sh
        if: steps.has-changed.outputs.changed == 'true'
      - uses: jakejarvis/s3-sync-action@master
        if: steps.has-changed.outputs.changed == 'true'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'artifacts'
