name: MLOps workflow
on: push
jobs:
  build-ingest:
    name: Build Ingest Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-ingest
      - run: |
          pwd
          find .
      - uses: actions/upload-artifact@v2
        with:
          name: ingest
          path: /home/runner/work/wgu-capstone/wgu-capstone/ingest.zip
