name: MLOps workflow
on: push
jobs:
  configure-workflow:
    name: 'Configure Workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: pipeline-has-changed
        with:
          paths: pipeline
      - uses: marceloprado/has-changed-path@v1
        id: stage1-has-changed
        with:
          paths: pipeline/stage1_ingest
      - uses: marceloprado/has-changed-path@v1
        id: stage2-has-changed
        with:
          paths: pipeline/stage2_clean
      - uses: marceloprado/has-changed-path@v1
        id: stage3-has-changed
        with:
          paths: pipeline/stage3_model
      - uses: marceloprado/has-changed-path@v1
        id: stage4-has-changed
        with:
          paths: pipeline/stage4_test
      - uses: marceloprado/has-changed-path@v1
        id: stage5-has-changed
        with:
          paths: pipeline/stage5_deploy
    outputs:
      pipeline-has-changed: ${{ steps.pipeline-has-changed.outputs.changed }}
      stage1-has-changed: ${{ steps.stage1-has-changed.outputs.changed }}
      stage2-has-changed: ${{ steps.stage2-has-changed.outputs.changed }}
      stage3-has-changed: ${{ steps.stage3-has-changed.outputs.changed }}
      stage4-has-changed: ${{ steps.stage4-has-changed.outputs.changed }}
      stage5-has-changed: ${{ steps.stage5-has-changed.outputs.changed }}
  build-ingest:
    if: ${{ needs.configure-workflow.outputs.stage1-has-changed == 'true' }}
    name: 'Build Stage 1: Ingest'
    needs: configure-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-ingest
      - uses: actions/upload-artifact@v2
        with:
          name: stage1_ingest
          path: stage1_ingest.zip
  build-clean:
    if: ${{ needs.configure-workflow.outputs.stage2-has-changed == 'true' }}
    name: 'Build Stage 2: Clean'
    needs: configure-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-clean
      - uses: actions/upload-artifact@v2
        with:
          name: stage2_clean
          path: stage2_clean.zip
  build-model:
    if: ${{ needs.configure-workflow.outputs.stage3-has-changed == 'true' }}
    name: 'Build Stage 3: Model'
    needs: configure-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-model
      - uses: actions/upload-artifact@v2
        with:
          name: stage3_model
          path: artifacts/*
  build-test:
    if: ${{ needs.configure-workflow.outputs.stage4-has-changed == 'true' }}
    name: 'Build Stage 4: Test'
    needs: configure-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-test
      - uses: actions/upload-artifact@v2
        with:
          name: stage4_test
          path: stage4_test.zip
  build-deploy:
    if: ${{ needs.configure-workflow.outputs.stage5-has-changed == 'true' }}
    name: 'Build Stage 5: Deploy'
    needs: configure-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-deploy
      - uses: actions/upload-artifact@v2
        with:
          name: stage5_deploy
          path: stage5_deploy.zip
  upload-artifacts:
    if: always()
    needs: [configure-workflow, build-ingest, build-clean, build-model, build-test, build-deploy]
    name: 'Upload Build Artifacts to S3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: ./.github/scripts/collect-build-artifacts.sh
      - run: ../.github/scripts/hash-zips.sh
        working-directory: ./artifacts
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'artifacts'
  terraform-plan:
    name: 'Terraform Plan'
    needs: upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrislennon/action-aws-cli@v1.1
      - uses: hashicorp/setup-terraform@v1
      - working-directory: ./infra
        run: |
          terraform init
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform-apply:  
    environment: Production
    name: 'Terraform Apply'
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrislennon/action-aws-cli@v1.1
      - uses: hashicorp/setup-terraform@v1
      - working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
